[project]
name = "websearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.6.3",
    "duckduckgo-search>=8.0.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]
